---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rollouts-role
  namespace: company
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
      - watch
  - apiGroups: ["apps","extensions"]
    resources:
      - deployments
      - deployments/scale
      - deployments/status
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - scale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollouts-role-binding
  namespace: company
subjects:
- kind: ServiceAccount
  name: admin-api-gateway
  namespace: company
- kind: ServiceAccount
  name: account-service
  namespace: company
roleRef:
  kind: Role
  name: rollouts-role
  apiGroup: rbac.authorization.k8s.io
