apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: bankvault
spec:
  size: 3
  image: vault:1.6.2

  unsealConfig:
    google:
      kmsKeyRing: "bank-vault-unseal-key"
      kmsCryptoKey: "bank-vault-unseal"
      kmsLocation: "global"
      kmsProject: "company-staging"
      storageBucket: "company-stage-bank-vault"

  serviceAccount: vault

  config:
    storage:
      gcs:
        bucket: "company-stage-bank-vault"
        ha_enabled: "true"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.bankvault:8200
    telemetry:
      statsd_address: localhost:9125
    ui: true

  externalConfig:
    policies:
      - name: allow_secrets
        rules: |
          path "secret/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: company
        rules: |
          path "*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: gmail
        rules: |
          path "*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: gcp_editor_access
        rules: |
          path "gcp/key/editor" {
            capabilities = ["read"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: company
            bound_service_account_names: "*"
            bound_service_account_namespaces: "*"
            policies: company
      - type: github
        config:
          organization: Freshly
        map:
          teams:
            company: company
          users:
            - jamalshahverdiyev: gmail

      - type: oidc
        config:
          oidc_discovery_url: ""
          oidc_client_id: ""
          oidc_client_secret: ""
          default_role: "gmail"
        roles:
          - name: gmail
            user_claim: "sub"
            allowed_redirect_uris:
              - https://company.infra.companyservices.net/ui/vault/auth/oidc/oidc/callback
            bound_audiences:
              - ""
            policies: "gmail"
            claim_mappings:
              email: email
              name: name
            oidc_scopes:
              - email
              - openid
            ttl: 1h
            verbose_oidc_logging: true
  credentialsConfig:
    env: GOOGLE_APPLICATION_CREDENTIALS
    path: /etc/gcp/service-account.json
    secretName: gcp-sa
