apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  namespace: company-mss
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.bankvault:8200" 
        vault.security.banzaicloud.io/vault-role: "freshly" 
        vault.security.banzaicloud.io/vault-skip-verify: "true" 
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls" 
        vault.security.banzaicloud.io/vault-agent: "false" 
        vault.security.banzaicloud.io/vault-path: "kubernetes/" 
    spec:
      serviceAccountName: default
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "for i in `seq 1000`; do sleep 1; echo $AWS_SECRET_ACCESS_KEY; done"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/demosecret/aws#AWS_SECRET_ACCESS_KEY
